### ISSUE TITLE
Question about sponsor option in this repo

### ISSUE THREAD

**Issue by NirmalSilwal** [thetechcommunity/thetechcommunity.github.io#1]
Hi there,

I can see the community location India in the org description. So I was wondering about the **sponsor button** available on this organization. On the [official page](https://github.com/sponsors) I can see sponsorship is not available in India. Is it that you used your bank information of any of eligible countries?

**Comment by AnkushSinghGandhi** [comment]
sponsering for organization is avail in india i think

**Comment by NirmalSilwal** [comment]
though github sponsor option is not availabe in India, maybe it is different for organization and personal projects, not sure!

**Comment by AnkushSinghGandhi** [comment]
yes it is different
